site_name: LLM Cody Wiki
site_description: Curated knowledge base for Large Language Models
site_url: https://example.com

# Material for MkDocs theme
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Meta:
      - Taxonomy: meta/taxonomy.md
      - Style Guide: meta/style-guide.md
      - Templates:
          - Article: meta/templates/article.md
  - Glossary: glossary.md
  - Resources: resources.md
  - FAQ: faq.md
  - Prompting: prompting/overview.md
  - Models: models/overview.md
  - Training:
      - Overview: training/overview.md
      - Swift (ms-swift): training/ms-swift.md
      - Unsloth: training/unsloth.md
      - Unsloth RL: training/unsloth-rl.md
  - Inference: inference/overview.md
  - Evaluation:
      - Overview: evaluation/overview.md
      - EvalScope: evaluation/evalscope.md
      - Ruler: evaluation/ruler.md
  - Datasets:
      - Overview: datasets/overview.md
      - easy-dataset: datasets/easy-dataset.md
  - Alignment & Safety: alignment-safety/overview.md
  - Agents:
      - Overview: agents/overview.md
      - LangGraph Monitoring: agents/langgraph-monitoring.md
  - Tooling:
      - Overview: tooling/overview.md
      - LiteLLM Local: tooling/litellm.md
      - OpenAI Harmony: tooling/openai-harmony.md
  - Infrastructure: infrastructure/overview.md
  - Applications: applications/overview.md
site_dir: site
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
