site_name: LLM Cody Wiki
site_description: Curated knowledge base for Large Language Models
site_url: https://example.com

# Material for MkDocs theme
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Meta:
      - Taxonomy: meta/taxonomy.md
      - Style Guide: meta/style-guide.md
      - Templates:
          - Article: meta/templates/article.md
  - Glossary: glossary.md
  - Resources: resources.md
  - FAQ: faq.md
  - Topics:
      - Prompting: prompting/overview.md
      - Models: models/overview.md
      - Training: training/overview.md
      - Inference: inference/overview.md
      - Evaluation: evaluation/overview.md
      - Datasets: datasets/overview.md
      - Alignment & Safety: alignment-safety/overview.md
      - Agents: agents/overview.md
      - Tooling: tooling/overview.md
      - Infrastructure: infrastructure/overview.md
      - Applications: applications/overview.md
site_dir: site
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
